const crypto = require('node:crypto');
const fs = require('node:fs/promises');
const path = require('node:path');
const config = require('./config');
function transform(value,type){ if(value==null)return null; const v=String(value).trim(); if(type==='number'){const n=Number(v.replace(/[^0-9.-]/g,'')); return Number.isFinite(n)?n:null;} return v; }
function extractBySelectors(html, schema={}){ const out={}; for(const [key,rule] of Object.entries(schema)){ const selector=typeof rule==='string'?rule:rule.selector; if(typeof selector!=='string'||selector.length>500){out[key]=null;continue;} const safe=selector.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'); let match; if(selector.startsWith('#')){const id=selector.slice(1).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');match=html.match(new RegExp(`<[^>]+id=["']${id}["'][^>]*>([\\s\\S]*?)<\\/[^>]+>`,'i'));} else if(selector.startsWith('.')){const cls=selector.slice(1).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');match=html.match(new RegExp(`<[^>]+class=["'][^"']*${cls}[^"']*["'][^>]*>([\\s\\S]*?)<\\/[^>]+>`,'i'));} else match=html.match(new RegExp(`<${safe}\\b[^>]*>([\\s\\S]*?)<\\/${safe}>`,'i')); const value=match?.[1]?.replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim()??null; out[key]=transform(value,typeof rule==='string'?'text':rule.transform||'text'); } return out; }
async function persistArtifacts(jobId,{html,screenshot,metadata}){ const dir=path.join(config.ARTIFACT_DIR,jobId); await fs.mkdir(dir,{recursive:true}); const artifacts={}; if(html){const file=path.join(dir,'page.html'); await fs.writeFile(file,html); artifacts.html=`artifacts/${jobId}/page.html`;} if(screenshot){const file=path.join(dir,'screenshot.png'); await fs.writeFile(file,screenshot); artifacts.screenshot=`artifacts/${jobId}/screenshot.png`;} if(metadata){const file=path.join(dir,'metadata.json'); await fs.writeFile(file,JSON.stringify(metadata,null,2)); artifacts.metadata=`artifacts/${jobId}/metadata.json`;} return artifacts; }
function hash(value){return crypto.createHash('sha256').update(value).digest('hex');}
module.exports={extractBySelectors,persistArtifacts,hash};
