const express=require('express'); const helmet=require('helmet'); const crypto=require('node:crypto'); const fs=require('node:fs'); const path=require('node:path'); const {WebSocketServer}=require('ws'); const {z}=require('zod'); const config=require('./config'); const {queue}=require('./queue'); const {saveJob,getJob,getEvents}=require('./store'); const {registry}=require('./observability'); const {logger}=require('./observability');
const app=express(); app.use(helmet()); app.use(express.json({limit:'1mb'}));
function auth(req,res,next){ if(req.path==='/health'||req.path==='/metrics')return next(); const supplied=req.get('authorization')?.replace(/^Bearer\s+/i,''); const valid=Boolean(supplied)&&[...config.apiKeys].some(key=>{const expected=Buffer.from(key);const actual=Buffer.from(supplied);return expected.length===actual.length&&crypto.timingSafeEqual(expected,actual);}); if(!valid) return res.status(401).json({error:'Unauthorized'}); next(); }
const jobSchema=z.object({url:z.string().url().max(2048),engine:z.enum(['auto','playwright','puppeteer']).optional(),mode:z.enum(['headless','headed']).optional(),waitUntil:z.enum(['load','domcontentloaded','networkidle']).optional(),timeoutMs:z.number().int().min(5000).max(180000).optional(),actions:z.array(z.record(z.string(),z.any())).max(50).optional(),extract:z.object({schema:z.record(z.string(),z.any()).optional()}).optional(),artifacts:z.object({html:z.boolean().optional(),screenshot:z.boolean().optional(),fullPage:z.boolean().optional()}).optional()});
app.use(auth); app.get('/health',(req,res)=>res.json({status:'ok',service:'nexus-engine-v2',redis:'connected',timestamp:new Date().toISOString()})); app.get('/metrics',async(req,res)=>{res.type(registry.contentType);res.end(await registry.metrics());});
app.post('/v1/jobs',async(req,res,next)=>{try{const data=jobSchema.parse(req.body);const id=crypto.randomUUID();await saveJob(id,{id,status:'queued',request:data,createdAt:Date.now()});await queue.add('browser-job',{...data},{jobId:id});res.status(202).json({id,status:'queued',eventsUrl:`/v1/jobs/${id}/events`});}catch(e){next(e);}});
app.get('/v1/jobs/:id',(req,res)=>getJob(req.params.id).then(job=>job?res.json(job):res.status(404).json({error:'Job not found'}))); app.get('/v1/jobs/:id/events',(req,res)=>getEvents(req.params.id).then(events=>res.json({events}))); app.post('/v1/jobs/:id/cancel',async(req,res)=>{const job=await queue.getJob(req.params.id);if(!job)return res.status(404).json({error:'Job not found'});await job.remove();await saveJob(req.params.id,{status:'cancelled',finishedAt:Date.now()});res.json({id:req.params.id,status:'cancelled'});}); app.get('/v1/jobs/:id/artifacts/:name',(req,res)=>{const safe=path.basename(req.params.name);const file=path.join(config.ARTIFACT_DIR,req.params.id,safe);if(!fs.existsSync(file))return res.status(404).end();res.sendFile(file);});
app.use((err,req,res,next)=>{logger.error({err},'request failed');res.status(err.name==='ZodError'?400:500).json({error:err.message||'Internal error'});});
const server=app.listen(config.PORT,()=>logger.info({port:config.PORT},'Nexus Engine API listening')); const wss=new WebSocketServer({server,path:'/v1/ws'}); wss.on('connection',ws=>ws.send(JSON.stringify({type:'ready'}))); module.exports={app,server};
